# Generated by Django 2.2.6 on 2019-11-10 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('street_address', models.CharField(max_length=300)),
                ('apartment_address', models.CharField(max_length=300)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
