# Generated by Django 2.2.6 on 2019-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refunds',
            name='issue_description',
            field=models.TextField(max_length=500),
        ),
    ]
