# Generated by Django 2.2.6 on 2019-11-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
    ]
